apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: datamesh-quickstart
    kind: datamesh
  name: datamesh-quickstart-datamesh-node
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
